apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: podtato-head-app-kargo
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: dev
      - stage: qs
      - stage: prod
  template:
    metadata:
      name: podtato-head-app-kargo-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: podtato-head-app:{{stage}}
    spec:
      project: default
      source:
        repoURL: 'https://github.com/dirien/gitops-promotion-tools-why-you-need-to-add-them-to-your-gitops-toolkit-in-2025.git'
        targetRevision: stage/{{stage}}
        path: .
      destination:
        server: https://kubernetes.default.svc
        namespace: podtato-head-app-kargo-{{stage}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: podtato-head-app
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: podtato-head-app
  namespace: podtato-head-app
spec:
  promotionPolicies:
  - stageSelector:
      name: qs
    autoPromotionEnabled: true
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: podtato-head-app-repo
  namespace: podtato-head-app
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: "https://github.com/dirien/gitops-promotion-tools-why-you-need-to-add-them-to-your-gitops-toolkit-in-2025.git"
  username: "dirien"
  password: "xxx"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: podtato-head-app-warehouse
  namespace: podtato-head-app
spec:
  freightCreationPolicy: Automatic
  interval: 30s
  subscriptions:
  - git:
      repoURL: "https://github.com/dirien/gitops-promotion-tools-why-you-need-to-add-them-to-your-gitops-toolkit-in-2025.git"
      includePaths:
      - app/
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: podtato-head-app
  annotations:
    kargo.akuity.io/color: red
spec:
  verification:
    analysisTemplates:
    - name: podtato-head-performance
    args:
    - name: namespace
      value: podtato-head-app-kargo-${{ ctx.stage }}
    - name: service-name
      value: podtato-head-app-kargo-${{ ctx.stage }}-entry
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: stageFolder
          value: stages/test
  requestedFreight:
  - origin:
      kind: Warehouse
      name: podtato-head-app-warehouse
    sources:
      direct: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: qs
  namespace: podtato-head-app
  annotations:
    kargo.akuity.io/color: green
spec:
  verification:
    analysisTemplates:
    - name: podtato-head-performance
    args:
    - name: namespace
      value: podtato-head-app-kargo-${{ ctx.stage }}
    - name: service-name
      value: podtato-head-app-kargo-${{ ctx.stage }}-entry
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: stageFolder
          value: stages/uat
  requestedFreight:
  - origin:
      kind: Warehouse
      name: podtato-head-app-warehouse
    sources:
      stages:
      - dev
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: podtato-head-app
  annotations:
    kargo.akuity.io/color: blue
spec:
  verification:
    analysisTemplates:
    - name: podtato-head-performance
    args:
    - name: namespace
      value: podtato-head-app-kargo-${{ ctx.stage }}
    - name: service-name
      value: podtato-head-app-kargo-${{ ctx.stage }}-entry
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: stageFolder
          value: stages/prod-nyc
  requestedFreight:
  - origin:
      kind: Warehouse
      name: podtato-head-app-warehouse
    sources:
      stages:
      - qs
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote
  namespace: podtato-head-app
spec:
  vars:
  - name: repoURL
    value: https://github.com/dirien/gitops-promotion-tools-why-you-need-to-add-them-to-your-gitops-toolkit-in-2025.git

  steps:
  - uses: git-clone
    as: clone
    config:
      repoURL: ${{ vars.repoURL }}
      checkout:
      - commit: ${{ commitFrom(vars.repoURL).ID }}
        path: ./src
      - branch: stage/${{ ctx.stage }}
        create: true
        path: ./out
  - uses: git-clear
    config:
      path: ./out
  - uses: helm-template
    config:
      releaseName: podtato-head-app-kargo-${{ ctx.stage }}
      path: ./src/app/chart/
      valuesFiles:
      - ./src/app/chart/values.yaml
      outPath: ./out/manifests.yaml
  - uses: git-commit
    as: commit
    config:
      path: ./out
      message: "Update manifests for stage ${{ ctx.stage }}"
  - uses: git-push
    config:
      path: ./out
      targetBranch: stage/${{ ctx.stage }}
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: podtato-head-performance
  namespace: podtato-head-app
spec: # Arguments that can be passed from the Stage
  args:
  - name: service-name
  - name: namespace
    value: default
  - name: latency-threshold-ms
    value: "100"  # Maximum acceptable latency in milliseconds
  - name: success-rate-threshold
    value: "0.95"  # Minimum 95% success rate

  metrics: # Metric 1: Check if the service is up and being scraped
  - name: service-availability
    initialDelay: 10s
    interval: 20s
    count: 3
    successCondition: result[0] >= 1
    failureLimit: 2
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        query: |
          up{job="{{ args.service-name }}",namespace="{{ args.namespace }}"}

  # Metric 2: Check average request latency is below threshold
  - name: average-latency
    initialDelay: 10s
    interval: 20s
    count: 3
    successCondition: result[0] < {{ args.latency-threshold-ms }}
    failureLimit: 2
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        query: |
          (
            rate(http_server_request_latency_seconds_sum{job="{{ args.service-name }}",namespace="{{ args.namespace }}",route!~"/assets|/parts/.*"}[2m])
            /
            rate(http_server_request_latency_seconds_count{job="{{ args.service-name }}",namespace="{{ args.namespace }}",route!~"/assets|/parts/.*"}[2m])
          ) * 1000

  # Metric 3: Check success rate (no 5xx errors)
  - name: success-rate
    initialDelay: 10s
    interval: 20s
    count: 3
    successCondition: result[0] >= {{ args.success-rate-threshold }}
    failureLimit: 2
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        query: |
          sum(rate(http_requests_total{job="{{ args.service-name }}",namespace="{{ args.namespace }}",route!~"/assets|/parts/.*",status_code!~"5.."}[2m]))
          /
          sum(rate(http_requests_total{job="{{ args.service-name }}",namespace="{{ args.namespace }}",route!~"/assets|/parts/.*"}[2m]))

  # Metric 4: Check p95 latency
  - name: p95-latency
    initialDelay: 10s
    interval: 20s
    count: 3
    successCondition: result[0] < {{ args.latency-threshold-ms }}
    failureLimit: 3
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        query: |
          histogram_quantile(0.95,
            sum(rate(http_server_request_latency_seconds_bucket{job="{{ args.service-name }}",namespace="{{ args.namespace }}",route!~"/assets|/parts/.*"}[2m])) by (le)
          ) * 1000
