apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
spec:
  destination:
    namespace: kargo
    server: https://kubernetes.default.svc
  project: infra
  source:
    repoURL: oci://ghcr.io/akuity/kargo-charts/kargo
    targetRevision: 1.7.5
    path: .
    helm:
      valuesObject:
        api:
          service:
            type: LoadBalancer
          adminAccount:
            passwordHash: $2a$10$Zrhhie4vLz5ygtVSaif6o.qN36jgs6vjtMBdM6yrU1FOeiAAMMxOm
            tokenSigningKey: iwishtowashmyirishwristwatch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
