apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-promoter
  namespace: argocd
spec:
  destination:
    namespace: promoter-system
    server: https://kubernetes.default.svc
  project: infra
  source:
    repoURL: https://argoproj-labs.github.io/gitops-promoter-helm/
    chart: gitops-promoter
    targetRevision: 0.18.0
    helm:
      valuesObject:
        rbac:
          helpers:
            enable: true
        controllerConfiguration:
          promotionStrategy:
            workQueue:
              requeueDuration: 30s
          changeTransferPolicy:
            workQueue:
              requeueDuration: 30s
          pullRequest:
            workQueue:
              requeueDuration: 30s
          commitStatus:
            workQueue:
              requeueDuration: 30s
          argocdCommitStatus:
            workQueue:
              requeueDuration: 30s
          timedCommitStatus:
            workQueue:
              requeueDuration: 30s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
