apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /spec/preserveUnknownFields
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: infra
  source:
    repoURL: 'oci://quay.io/jetstack/charts/cert-manager'
    targetRevision: v1.18.2
    path: .
    helm:
      valuesObject:
        crds: 
          enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
