apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /spec/preserveUnknownFields
  destination:
    namespace: argo-rollouts
    server: https://kubernetes.default.svc
  project: infra
  source:
    repoURL: 'oci://ghcr.io/argoproj/argo-helm/argo-rollouts'
    targetRevision: 2.40.4
    path: .
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
