apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: infra
  sources:
  - repoURL: oci://ghcr.io/argoproj/argo-helm/argo-cd
    targetRevision: 9.1.4
    path: .
    helm:
      valueFiles:
      - $values/gitops/base-tools/argocd/argocd-values.yaml
  - repoURL: https://github.com/dirien/gitops-promotion-tools-why-you-need-to-add-them-to-your-gitops-toolkit-in-2025
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
